# name: Continuous Integration

# on:
#   push:
#     branches:
#       - main  # Change this to your default branch if necessary
#   pull_request:
#     branches:
#       - main  # Run tests on pull requests targeting the main branch

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.10'  # Specify your Python version

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt  # Adjust if you have specific requirements

#       - name: Run tests
#         run: |
#           pytest  # Run your test cases using pytest
name: CI-CD pipeline 
on:
  push:
    branches:
      - main  # Change this to your default branch if necessary
  pull_request:
    branches:
    - main  # Run tests on pull requests targeting the main branch
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/ # Run your test cases using pytest