name: CI-CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Debug Python Environment
        run: |
          python --version
          pip --version
          pip list
          which python
          which pytest

      - name: Run tests
        run: pytest
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Chekout code
        uses: actions/checkout@v2

      - name: Install vercel cli
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
        run: vercel --prod --token=$VERCEL_TOKEN